import Link from "next/link";
import { requireViewer } from "@/lib/guard";
import { recentNotifications, unreadCount } from "@/lib/notifications";
import { Breadcrumb, Panel } from "@/components/dashboard/widgets";
import { BroadcastForm, MarkAllRead, MarkOneRead } from "./forms";

/*
 * Notifications (Phase 9).
 *
 * requireViewer — your notifications are yours, and reading them is not a
 * privilege. Every query here is scoped to `viewer.id`; there is no path that
 * takes an id from the request.
 *
 * Broadcasting is a capability (`notifications.broadcast`), not an assumption that
 * seniority carries the right to interrupt the whole company.
 */
export const metadata = { title: "Notifications" };

export default async function NotificationsPage() {
  const viewer = await requireViewer();
  const [items, unread] = await Promise.all([
    recentNotifications(viewer.id, 50),
    unreadCount(viewer.id),
  ]);

  return (
    <div className="mx-auto flex max-w-3xl flex-col gap-4">
      <Breadcrumb
        trail={[{ label: "Dashboards", href: "/app" }, { label: "Notifications" }]}
      />

      <div className="flex flex-wrap items-end justify-between gap-4">
        <div>
          <h1 className="text-[26px] font-semibold tracking-[-0.02em]">Notifications</h1>
          <p className="mt-1 text-[15px] text-text-secondary">
            {unread > 0
              ? `${unread} unread.`
              : "Nothing unread."}{" "}
            Every one of these is something that actually happened.
          </p>
        </div>
        {unread > 0 && <MarkAllRead />}
      </div>

      {viewer.can("notifications.broadcast") && (
        <Panel>
          <h2 className="text-sm font-semibold uppercase tracking-[0.08em] text-text-muted">
            Broadcast
          </h2>
          <p className="mt-3 max-w-2xl text-sm leading-relaxed text-text-secondary">
            Goes to everyone who works here. Collaborators are deliberately not
            included — a company announcement is not addressed to an external
            partner, and quietly including them would send internal context outside
            the company.
          </p>
          <div className="mt-5">
            <BroadcastForm />
          </div>
        </Panel>
      )}

      <Panel>
        {items.length === 0 ? (
          <p className="text-[15px] leading-relaxed text-text-muted">
            Nothing yet. Notifications are generated by real events — a leave request
            waiting on you, a reply to a support request, an invitation accepted.
            Nothing here is invented to fill the space.
          </p>
        ) : (
          <ul className="flex flex-col">
            {items.map((n) => (
              <li
                key={n.id}
                className={`flex flex-wrap items-start gap-3 border-b border-border-subtle py-4 last:border-0 ${
                  n.readAt ? "" : "-mx-2 rounded-card bg-brand-cyan/[0.04] px-2"
                }`}
              >
                {!n.readAt && (
                  <span className="mt-2 h-2 w-2 shrink-0 rounded-full bg-brand-cyan" />
                )}
                <span className="min-w-0 flex-1">
                  <span
                    className={`block text-[15px] ${
                      n.readAt ? "text-text-secondary" : "font-medium text-text-primary"
                    }`}
                  >
                    {n.title}
                  </span>
                  {n.body && (
                    <span className="mt-0.5 block text-sm text-text-muted">{n.body}</span>
                  )}
                  <span className="mt-1 block text-xs text-text-muted">
                    {n.createdAt.toLocaleString("en-GB", {
                      day: "numeric",
                      month: "short",
                      hour: "2-digit",
                      minute: "2-digit",
                    })}
                  </span>
                </span>

                <span className="flex shrink-0 items-center gap-3">
                  {n.href && (
                    // A doorbell, not a door: the page behind this re-checks
                    // server-side, so a stale link opens nothing it should not.
                    <Link
                      href={n.href}
                      className="text-sm font-medium text-brand-cyan hover:text-brand-teal"
                    >
                      Open
                    </Link>
                  )}
                  {!n.readAt && <MarkOneRead id={n.id} />}
                </span>
              </li>
            ))}
          </ul>
        )}
      </Panel>
    </div>
  );
}
